spring:
  application:
    name: im-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
        file-extension: yaml
  config:
    import: nacos:im-service.yaml?refreshEnabled=true&group=DEFAULT_GROUP
