server:
  port: 8087

spring:
  application:
    name: agent-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
        file-extension: yaml
        group: DEFAULT_GROUP
        refresh-enabled: true
  config:
    import:
      - nacos:common
      - nacos:agent-service
  elasticsearch:
    uris: http://localhost:9200
  ai:
    vectorstore:
      elasticsearch:
        initialize-schema: true
        index-name: cm-agent-knowledge
        dimensions: 1536
        similarity: cosine

logging:
  level:
    com.cloudmall.agent: debug
