spring:
  application:
    name: order-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
        file-extension: yaml
        group: DEFAULT_GROUP
        refresh-enabled: true
  config:
    import:
      - nacos:common
      - nacos:order-service
