server:
  port: 8084

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cm_order?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai

mybatis-plus:
  type-aliases-package: com.cloudmall.order.entity
