server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cm_user?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai

mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.cloudmall.user.entity
